services:
  # Tên dịch vụ (có thể đặt tùy ý, ví dụ: gpu-workspace)
  gpu-workspace:
    # 1. Chỉ định nơi Docker Compose tìm file Dockerfile để tự động build
    image: nguyenquocphu/cuda13-vllm
    # 2. Đặt tên cho container cho dễ nhìn thay vì chuỗi ID ngẫu nhiên
    container_name: dflash-dev-env
    
    # 3. Kích hoạt GPU (Tương đương cờ --gpus all)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # Đã chọn device_ids thì KHÔNG ĐƯỢC dùng count: all nữa
              device_ids: ['0']
              capabilities: [gpu]
        # Thêm giới hạn RAM ở đây (máy bạn có 7.4GB, 80% là khoảng 6GB)
        limits:
          memory: 45G
    
    # 5. Map port (Tương đương cờ -p)
    ports:
      - "8008:8000"
    
    # 7. Map thư mục Cache từ Server vào Container (Tương đương cờ --mount type=bind)
    volumes:
      - ~/5080_cuda13/venv:/opt/venv
      - ~/5080_cuda13/dflash:/workspace/dflash
      - ~/.cache/uv:/root/.cache/uv
      - ~/.cache/huggingface:/root/.cache/huggingface
    
    # 6. Giữ container luôn mở terminal thay vì chạy xong rồi tắt ngúm
    tty: true
    stdin_open: true
    ipc: host

